liip_imagine: 
  # As mentioned above, gd, imagick or gmagick are possible
  driver: "gd"
  # This is where all the filters sets are located
  filter_sets:

        downscale_filter:
        
            jpeg_quality: 70
            png_compression_level: 8

            filters:

                # use and setup the "downscale" filter
                downscale:

                    # input 1980x1280px -> output 792x512px
                    by: 0.5

                watermark_image:

                    image: "/watermark.png"

                    size: 0.25

                    position: topright
                
                auto_rotate: ~
                strip: ~
