twig:
    default_path: '%kernel.project_dir%/templates'

    paths:
        '%kernel.project_dir%/public/assets/img/front-page-images': images
    
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'